import "./globals.css";
import "./layout.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Header from "./Components/Header/Header";
import Footer from "./Components/Footer/Footer";
import Main from "./Components/Main/Main";

export default function RootLayout() {
  return (
    <html lang="en">
      <body>
        <Header />
        <Main />
        <Footer />
        
      </body>
    </html>
  );
}
